[package]
name = "redjubjub"
edition = "2018"
# When releasing to crates.io:
# - Update html_root_url
# - Update CHANGELOG.md
# - Create git tag.
version = "0.1.1"
authors = ["Henry de Valence <hdevalence@hdevalence.ca>"]
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ZcashFoundation/redjubjub"
categories = ["cryptography", "zcash"]
keywords = ["cryptography", "crypto", "jubjub", "redjubjub", "zcash"]
description = "A mostly-standalone implementation of the RedJubjub signature scheme."

[package.metadata.docs.rs]
features = ["nightly"]

[dependencies]
rand_core = "0.5"
thiserror = "1.0"
blake2b_simd = "0.5"
jubjub = "0.3"
serde = { version = "1", optional = true, features = ["derive"] }

[dev-dependencies]
rand = "0.7"
rand_chacha = "0.2"
proptest = "0.10"
lazy_static = "1.4"
bincode = "1"

[features]
nightly = []
default = ["serde"]
