name: Coverage

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  coverage:
    name: Coverage (+nightly)
    timeout-minutes: 30
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov cargo command
        run: cargo install cargo-llvm-cov

      - name: Generate code coverage
        env:
          CARGO_INCREMENTAL: 0
        run: cargo llvm-cov --lcov > lcov.info

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v5.3.1
